server:
  port: 8080

spring:
  application:
    name: rabbitmq-demo-order-8080
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/spring_alibaba_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimeZone=UTC
    username: root
    password: root3306
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*.xml
