server:
  port: 80
spring:
  application:
    name: rabbitmq-demo-consumer-80
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

rabbitmq-demo-order-8080:
  ribbon:
    listOfServers: http://localhost:8080